import { Header } from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ContextProvier } from "@/contexts/Context";
import { ThemeContext } from "@/contexts/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" className="dark" style={{ colorScheme: "dark" }}>
      <body className={inter.className}>
        <ThemeContext>
          <ContextProvier>
            <Header />
            {children}
          </ContextProvier>
        </ThemeContext>
      </body>
    </html>
  );
}
